const MINUTE = 60 * 1000;
const HOUR = 60 * MINUTE;

export const BATTERY_ICON_THRESHOLD = 0.3;
export const BATTERY_LOW_FILTER_THRESHOLD = 0.3;
export const BATTERY_HIGH_FILTER_THRESHOLD = 0.7;
export const LEVEL_LOW_FILTER_THRESHOLD = 0.3;
export const LEVEL_HIGH_FILTER_THRESHOLD = 0.7;
export const OFFLINE_ICON_TIMEOUT = 5 * HOUR;
export const OFFLINE_FILTER_TIMEOUT = 5 * HOUR;
